#!/usr/bin/env python3
"""Convert data/players.json -> data/players.js (self.PLAYERS_DATA = {...}; `self` is window on the page and the worker global in sw.js)
so the site works from file:// and GitHub Pages subpaths without fetch().
Usage: python3 tools/build_data_js.py"""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def build():
    src = os.path.join(ROOT, "data", "players.json")
    dst = os.path.join(ROOT, "data", "players.js")
    data = json.load(open(src, encoding="utf-8"))
    # factCheck notes are for editors, not the site: drop them to trim first-load JS
    for pl in data.get("players", []):
        pl.pop("factCheck", None)
    body = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    # "</script>" inside a string would terminate the tag; make it safe.
    body = body.replace("</", "<\\/")
    with open(dst, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/build_data_js.py - do not edit by hand.\n")
        f.write("self.PLAYERS_DATA = " + body + ";\n")
    print(f"wrote data/players.js ({os.path.getsize(dst)} bytes, {len(data.get('players', []))} players)")


if __name__ == "__main__":
    build()
